const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.TextBox.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{background: 0},
	{sphere1: 0},
	{questionText: 0},
	{TextInput: 0},
	{Text: 0},
	{answr: 0},
	{answer2: 0},
	{answer1: 0},
	{correcttext1: 0},
	{wrongtext: 0},
	{Mouse: 0},
	{Sphere2: 0},
	{Sphere3: 0},
	{Sphere4: 0},
	{Sphere5: 0},
	{questionpanel: 0},
	{wrongtext1: 0},
	{correcttextt1: 0},
	{questionpanel2: 0},
	{Text2: 0},
	{answer21: 0},
	{answer22: 0},
	{answer23: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{answer31: 0},
	{answer32: 0},
	{answer33: 0},
	{Sprite5: 0},
	{answer41: 0},
	{answer42: 0},
	{answer43: 0},
	{Sprite6: 0},
	{answer51: 0},
	{answer52: 0},
	{answer53: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	sphere1: class extends self.ISpriteInstance {},
	questionText: class extends self.ITextInputInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Text: class extends self.ITextInstance {},
	answr: class extends self.IButtonInstance {},
	answer2: class extends self.IButtonInstance {},
	answer1: class extends self.IButtonInstance {},
	correcttext1: class extends self.ITextInstance {},
	wrongtext: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Sphere2: class extends self.ISpriteInstance {},
	Sphere3: class extends self.ISpriteInstance {},
	Sphere4: class extends self.ISpriteInstance {},
	Sphere5: class extends self.ISpriteInstance {},
	questionpanel: class extends self.ISpriteInstance {},
	wrongtext1: class extends self.ITextInstance {},
	correcttextt1: class extends self.ITextInstance {},
	questionpanel2: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	answer21: class extends self.IButtonInstance {},
	answer22: class extends self.IButtonInstance {},
	answer23: class extends self.IButtonInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	answer31: class extends self.IButtonInstance {},
	answer32: class extends self.IButtonInstance {},
	answer33: class extends self.IButtonInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	answer41: class extends self.IButtonInstance {},
	answer42: class extends self.IButtonInstance {},
	answer43: class extends self.IButtonInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	answer51: class extends self.IButtonInstance {},
	answer52: class extends self.IButtonInstance {},
	answer53: class extends self.IButtonInstance {}
}